
language: php

dist: bionic
sudo: required

services:
  mysql

addons:
  # firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 7.3
      env:
      - MOODLE_BRANCH=master
      - DB=pgsql

    - php: 7.2
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli

    - php: 7.3
      env:
        - MOODLE_BRANCH=MOODLE_36_STABLE
        - DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - moodle-plugin-ci add-plugin --clone https://github.com/blackboard-open-source/moodle-theme_snap.git
  - moodle-plugin-ci add-plugin --clone https://github.com/tetecriizz/eudecustom.git
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit --coverage-text

  # The following line is a temporary work-around for https://tracker.moodle.org/browse/MDL-66378.
  # Once that is fixed, this line can go.
  # - curl https://github.com/timhunt/php-webdriver/commit/7a0aa38f591b7395939df25d8cb6677bf99a481f.patch | git apply --directory moodle/vendor/instaclick/php-webdriver
  # - moodle-plugin-ci behat --profile chrome