language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

addons:
  apt:
    packages:
     - chromium-chromedriver
env:
  global:
    - MOODLE_START_BEHAT_SERVERS=NO
    - DB=mysqli
    - MOODLE_CI_VER=1
    - MOODLE_DIR=/home/travis/build/moodle
    - MOODLE_SELENIUM_JAR=/home/travis/build/moodle/selenium.jar

matrix:
 include:
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_37_STABLE MOODLE_CI_VER=2

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - sleep 10

install:
  - moodle-plugin-ci install
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -Dwebdriver.chrome.driver=/usr/lib/chromium-browser/chromedriver -jar ${MOODLE_SELENIUM_JAR} -log /tmp/selenium.log &
  - php -t ${MOODLE_DIR} -S localhost:8000 > /tmp/php-access.log 2> /tmp/php-error.log &
  - sleep 5s

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --moodle=${MOODLE_DIR} --auto-rerun=0