language: php

sudo: true

services:
  mysql

addons:
  # firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.1

env:
 global:
  - MOODLE_BRANCH=MOODLE_37_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-poet
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-chrome:3

install:
  # - moodle-plugin-ci add-plugin --clone https://github.com/tetecriizz/eudecustom.git
  - moodle-plugin-ci add-plugin --clone https://github.com/blackboard-open-source/moodle-theme_snap
  - moodle-plugin-ci install
  - curl -L -s -o /home/travis/build/moodle/selenium34.jar http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
  - curl -L -s -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - sudo tar -C /usr/local/bin/ -xzf /tmp/geckodriver.tar.gz
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver -Dwebdriver.firefox.bin=/usr/bin/firefox -Dwebdriver.firefox.marionette=1 -jar /home/travis/build/moodle/selenium34.jar -log /tmp/selenium.log &
  - php -t /home/travis/build/moodle -S 127.0.0.1:8000 > /tmp/php-access.log 2> /tmp/php-error.log &
  - sleep 5s

script:
  # - moodle-plugin-ci phplint
  # - moodle-plugin-ci phpcpd
  # - moodle-plugin-ci phpmd
  # - moodle-plugin-ci codechecker
  # - moodle-plugin-ci codechecker --standard poet
  # - moodle-plugin-ci csslint
  # - moodle-plugin-ci shifter
  # - moodle-plugin-ci jshint # da error 
  # - moodle-plugin-ci validate
  # - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat # da error de selenium 
  # - moodle-plugin-ci behat --tags=@local_eudecustom
  # - moodle-plugin-ci phpunit --coverage-text