language: php

sudo: true

services:
  - mysql

addons:
  # firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.1
 env: MOODLE_CI_VER=2

env:
 global:
  - MOODLE_BRANCH=MOODLE_37_STABLE
  - MOODLE_START_BEHAT_SERVERS=NO
  - MOODLE_CI_VER=1
  - MOODLE_DIR=/home/travis/build/moodle
  - MOODLE_SELENIUM_JAR=/home/travis/build/moodle/selenium.jar

 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  # - phpenv config-rm xdebug.ini
  # - cd ../..
  # - composer selfupdate
  # - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-poet
  # - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-chrome:3
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - sleep 10

install:
  # - moodle-plugin-ci add-plugin --clone https://github.com/tetecriizz/eudecustom.git
  - moodle-plugin-ci add-plugin --clone https://github.com/blackboard-open-source/moodle-theme_snap
  - moodle-plugin-ci install
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -Dwebdriver.chrome.driver=/usr/lib/chromium-browser/chromedriver -jar ${MOODLE_SELENIUM_JAR} -log /tmp/selenium.log &
  - php -t ${MOODLE_DIR} -S localhost:8000 > /tmp/php-access.log 2> /tmp/php-error.log &
  - sleep 5s

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  # - moodle-plugin-ci jshint # da error 
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --moodle=${MOODLE_DIR} --auto-rerun=0 # da error de selenium 
  # - moodle-plugin-ci behat --tags=@local_eudecustom
  - moodle-plugin-ci phpunit --coverage-text